// ============================================================================
// SERVICE: DATABASE SERVICE (ai-qa.json LOCAL STORAGE)
// This file acts as a lightweight, file-based database for the backend.
// It stores and manages all QA test generation and snippet analysis records
// in a single JSON file (`ai-qa.json`) with concurrency-safe atomic operations.
// ============================================================================

// Import asynchronous promise-based file system methods to read/write JSON data without blocking the Node event loop.
import { promises as fs } from 'fs';
// Import synchronous file system methods specifically for fast existence checking during startup.
import fsSync from 'fs';
// Import Node.js path utility to resolve reliable, cross-platform absolute file paths.
import path from 'path';
// Import v4 from uuid to generate unique, random UUID identifiers for every analysis session.
import { v4 as uuidv4 } from 'uuid';

// ----------------------------------------------------------------------------
// DATABASE FILE LOCATION & CONCURRENCY QUEUE
// ----------------------------------------------------------------------------

// Constructs the absolute path to the local database file (`backend/ai-qa.json`).
// WHAT: Resolves path relative to the current directory (`__dirname`).
// WHY: Ensures the database file is always created and found in the backend root directory regardless of where the server was launched from.
// HOW: Used by all file read/write database operations below.
const DB_FILE = path.join(__dirname, '..', 'ai-qa.json');

// Holds the promise chain used as a sequential lock to prevent race conditions during concurrent file writes.
// WHAT: An in-memory promise initialized to an immediately resolved state.
// WHY: Node.js handles multiple requests asynchronously; without locking, concurrent file writes can corrupt the JSON file.
// HOW: Chained inside the `runLocked` helper function below.
let dbPromise = Promise.resolve();

// Concurrency locker that serializes all database read/write operations sequentially.
// WHAT: Takes an asynchronous database operation function (`op`) and chains it onto `dbPromise`.
// WHY: Ensures only one file system read-modify-write operation happens at any given moment, preventing data loss.
// HOW: Every exported function (`createAnalysis`, `updateAnalysis`, etc.) wraps its work with `runLocked`.
async function runLocked<T>(op: () => Promise<T>): Promise<T> {
    // Schedule the incoming operation to execute strictly after the previous operation finishes.
    const next = dbPromise.then(op);
    // Update dbPromise to wait for 'next' to complete (handling both success and failure so the queue never freezes).
    dbPromise = next.then(() => {}, () => {});
    // Return the result of the queued operation to the caller.
    return next;
}

// ----------------------------------------------------------------------------
// DATA MODELS / TYPES
// ----------------------------------------------------------------------------

// TypeScript interface representing a single QA analysis record.
// WHAT: Defines the exact schema of each analysis job stored in `ai-qa.json`.
// WHY: Enforces strict type safety across backend routes and client responses.
// HOW: Used by `server.ts` to inspect status, retrieve generated tests, and return history to the frontend.
export interface AnalysisRecord {
    // Unique identifier for the analysis session (UUID v4).
    id: string;
    // Client identifier generated by the frontend for user session isolation.
    client_id: string;
    // Target GitHub repository URL or 'Code Snippet Debugging' identifier.
    repo_url: string;
    // Current lifecycle stage of the analysis pipeline.
    status: 'STARTED' | 'GENERATING_TESTS' | 'TESTS_GENERATED' | 'RUNNING_TESTS' | 'COMPLETED' | 'FAILED' | 'ANALYSING';
    // ISO 8601 timestamp string marking when the job was created.
    created_at: string;
    // Name of the generated test file (e.g., 'generated-1712345678.spec.ts').
    test_file?: string;
    // Generated executable test suite source code (e.g., Playwright test script).
    test_code?: string;
    // Generated CI/CD pipeline configuration code (e.g., GitHub Actions YAML).
    cicd_code?: string;
    // Full Markdown diagnostic output or Playwright terminal execution log.
    playwright_output?: string;
    // Total duration of the analysis process in seconds.
    total_duration?: number;
    // Summary of detected tech stack (e.g., 'React, Express | TypeScript, Jest').
    framework_signature?: string;
}

// Interface representing the top-level structure of the JSON database.
// WHAT: Defines the JSON root object containing an array of analyses.
// WHY: Matches the structure written to and read from `ai-qa.json`.
interface Database {
    analyses: AnalysisRecord[];
}

// ----------------------------------------------------------------------------
// DATABASE INITIALIZATION
// ----------------------------------------------------------------------------

// Initializes the database file when the backend server boots up.
// WHAT: Checks if `ai-qa.json` exists; if not, creates it with an empty analyses array.
// WHY: Guarantees that subsequent read/write calls never fail due to a missing file.
// HOW: Called inside `app.listen()` in `backend/server.ts`.
export async function initDb() {
    return runLocked(async () => {
        try {
            // Check synchronously if the database file already exists.
            if (!fsSync.existsSync(DB_FILE)) {
                // Prepare default database schema with an empty analyses list.
                const initialDb: Database = { analyses: [] };
                // Write the initial formatted JSON string to disk.
                await fs.writeFile(DB_FILE, JSON.stringify(initialDb, null, 2), 'utf-8');
                console.log("📁 Initialized Local JSON database.");
            } else {
                console.log("📁 Local JSON database loaded.");
            }
        } catch (error) {
            // Log any startup storage error to the console.
            console.error("Error initializing local database:", error);
        }
    });
}

// ----------------------------------------------------------------------------
// CRUD OPERATIONS
// ----------------------------------------------------------------------------

// Creates a new analysis job record and persists it to disk.
// WHAT: Generates a new UUID, constructs an initial AnalysisRecord with 'STARTED' status, and appends it to `ai-qa.json`.
// WHY: Gives the frontend an immediate `analysisId` to track progress via SSE streaming.
// HOW: Called at the start of `/api/analyze` and `/api/analyze-snippet` in `server.ts`.
export async function createAnalysis(repoUrl: string, clientId: string): Promise<string> {
    return runLocked(async () => {
        // Read raw JSON text from the database file.
        const data = await fs.readFile(DB_FILE, 'utf-8');
        // Parse raw text into structured JavaScript object.
        const db: Database = JSON.parse(data);
        // Generate a new unique session identifier.
        const newId = uuidv4();
        // Construct the initial record with starting metadata.
        const newRecord: AnalysisRecord = {
            id: newId,
            client_id: clientId,
            repo_url: repoUrl,
            status: 'STARTED',
            created_at: new Date().toISOString()
        };
        // Add the new record to the in-memory array.
        db.analyses.push(newRecord);
        // Persist updated database back to the file system.
        await fs.writeFile(DB_FILE, JSON.stringify(db, null, 2), 'utf-8');
        // Return the generated analysis ID to the caller.
        return newId;
    });
}

// Updates specific fields of an existing analysis record.
// WHAT: Reads database, finds record by ID, merges partial updates, and writes back.
// WHY: Allows the analysis pipeline to update status, test code, AI reports, and execution time incrementally.
// HOW: Called throughout `server.ts`, `worker-entry.ts`, and background async tasks.
export async function updateAnalysis(id: string, updates: Partial<AnalysisRecord>) {
    return runLocked(async () => {
        // Read raw database content.
        const data = await fs.readFile(DB_FILE, 'utf-8');
        // Parse content into object.
        const db: Database = JSON.parse(data);
        // Find index of the record matching the provided ID.
        const index = db.analyses.findIndex((a) => a.id === id);
        // If the record exists in the database, merge updates.
        if (index > -1) {
            db.analyses[index] = { ...db.analyses[index], ...updates };
            // Save modified records array back to ai-qa.json.
            await fs.writeFile(DB_FILE, JSON.stringify(db, null, 2), 'utf-8');
        }
    });
}

// Retrieves analysis history, optionally filtered by client ID.
// WHAT: Reads all records, filters by `clientId` if provided, and sorts by most recent first.
// WHY: Feeds the sidebar history list in the frontend dashboard for the active user.
// HOW: Called by the `GET /api/analyses` endpoint in `server.ts`.
export async function getAnalyses(clientId?: string): Promise<AnalysisRecord[]> {
    return runLocked(async () => {
        // Read database file contents.
        const data = await fs.readFile(DB_FILE, 'utf-8');
        // Parse contents into database structure.
        const db: Database = JSON.parse(data);
        let results = db.analyses;
        // Filter by clientId if requested (session isolation).
        if (clientId) {
            results = results.filter(a => a.client_id === clientId);
        }
        // Return records sorted in descending order (newest first).
        return results.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
    });
}

// Fetches a single analysis record by its unique ID.
// WHAT: Searches `analyses` array for matching ID and returns record or null.
// WHY: Used to inspect record details during background processing or worker execution.
// HOW: Exported for internal lookups and `worker-entry.ts`.
export async function getAnalysisById(id: string): Promise<AnalysisRecord | null> {
    return runLocked(async () => {
        // Read file contents.
        const data = await fs.readFile(DB_FILE, 'utf-8');
        // Parse JSON data.
        const db: Database = JSON.parse(data);
        // Find and return matching record, or null if not found.
        return db.analyses.find((a) => a.id === id) || null;
    });
}

// Deletes an analysis record from the database by ID.
// WHAT: Filters out the record with the matching ID and saves the file.
// WHY: Allows users to remove old or unwanted analysis runs from their history.
// HOW: Called by the `DELETE /api/analyses/:id` endpoint in `server.ts`.
export async function deleteAnalysis(id: string) {
    return runLocked(async () => {
        // Read current database records.
        const data = await fs.readFile(DB_FILE, 'utf-8');
        // Parse JSON string into database object.
        const db: Database = JSON.parse(data);
        // Store length before deletion to detect whether record existed.
        const originalCount = db.analyses.length;
        // Filter out the item matching the given ID.
        db.analyses = db.analyses.filter((a) => a.id !== id);
        // If count decreased, record was found and removed; save file.
        if (db.analyses.length < originalCount) {
            await fs.writeFile(DB_FILE, JSON.stringify(db, null, 2), 'utf-8');
        } else {
            // Throw error if ID was not found so API can return 404.
            throw new Error("Analysis record not found.");
        }
    });
}
