import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { marked } from 'marked';

interface AnalysisRecord {
  id: string;
  repo_url: string;
  status: string;
  created_at: string;
  playwright_output?: string;
  test_code?: string;
  cicd_code?: string;
  total_duration?: number;
  framework_signature?: string;
}

export async function generateClientPDF(run: AnalysisRecord) {
  const date = new Date(run.created_at).toLocaleString();
  const title = run.repo_url === 'Code Snippet Debugging' ? 'Snippet Diagnostic Report' : 'Repository Audit Report';
  
  // 1. Prepare the HTML Content
  const proseHtml = marked.parse(run.playwright_output || '');
  const metrics = parseMetrics(run);
  
  let metricsHtml = '';
  if (metrics) {
    if (metrics.type === 'snippet') {
      metricsHtml = `
        <div class="metrics-grid">
          <div class="metric-card metric-error">
            <div class="label">Error Type</div>
            <div class="value">${metrics.errorType}</div>
          </div>
          <div class="metric-card metric-warning">
            <div class="label">Line Number</div>
            <div class="value">${metrics.errorLine}</div>
          </div>
          <div class="metric-card metric-success">
            <div class="label">Result</div>
            <div class="value">${metrics.hasFix ? 'Fixed' : 'Analyzed'}</div>
          </div>
        </div>
      `;
    } else {
      metricsHtml = `
        <div class="metrics-grid">
          <div class="metric-card metric-info">
            <div class="label">Execution Time</div>
            <div class="value">${metrics.duration}s</div>
          </div>
          <div class="metric-card metric-warning">
            <div class="label">Framework</div>
            <div class="value">${metrics.framework}</div>
          </div>
          <div class="metric-card ${run.status === 'COMPLETED' ? 'metric-success' : 'metric-error'}">
            <div class="label">Status</div>
            <div class="value">${run.status === 'COMPLETED' ? 'Success' : run.status}</div>
          </div>
        </div>
      `;
    }
  }

  const testCodeHtml = run.test_code ? `
    <div class="section-title">Playwright Test Suite</div>
    <pre class="code-block"><code>${escapeHtml(run.test_code)}</code></pre>
  ` : '';

  const cicdCodeHtml = run.cicd_code ? `
    <div class="section-title">CI/CD Pipeline Configuration</div>
    <pre class="code-block"><code>${escapeHtml(run.cicd_code)}</code></pre>
  ` : '';

  const fullHtml = `
    <div id="pdf-template" style="width: 800px; padding: 40px; background: #f8fafc; color: #0f172a; font-family: sans-serif; line-height: 1.6;">
      <div style="border-bottom: 2px solid #4f46e5; padding-bottom: 20px; margin-bottom: 30px;">
        <h1 style="font-size: 28px; margin: 0; font-weight: 800;">${title}</h1>
        <div style="display: flex; justify-content: space-between; font-size: 12px; color: #64748b; margin-top: 10px;">
          <span>Target: <strong style="color: #4f46e5;">${run.repo_url}</strong></span>
          <span>${date}</span>
        </div>
      </div>
      
      ${metricsHtml}
      
      <div style="background: white; border: 1px solid #e2e8f0; border-radius: 12px; padding: 30px; margin-bottom: 30px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);">
        ${proseHtml}
      </div>
      
      ${testCodeHtml}
      ${cicdCodeHtml}
      
      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #94a3b8; display: flex; justify-content: space-between; text-transform: uppercase;">
        <span>Generated by AI QA Engineer</span>
        <span>Premium Audit Report</span>
      </div>
      
      <style>
        .metrics-grid { display: flex; gap: 15px; margin-bottom: 30px; }
        .metric-card { flex: 1; background: white; border: 1px solid #e2e8f0; border-radius: 8px; padding: 15px; border-left: 4px solid #cbd5e1; }
        .metric-card .label { font-size: 10px; font-weight: 800; color: #64748b; text-transform: uppercase; margin-bottom: 5px; }
        .metric-card .value { font-size: 16px; font-weight: 800; }
        .metric-error { border-left-color: #ef4444; } .metric-error .value { color: #ef4444; }
        .metric-warning { border-left-color: #f59e0b; } .metric-warning .value { color: #f59e0b; }
        .metric-success { border-left-color: #10b981; } .metric-success .value { color: #10b981; }
        .metric-info { border-left-color: #3b82f6; } .metric-info .value { color: #3b82f6; }
        .section-title { font-size: 14px; font-weight: 800; color: #4f46e5; margin-top: 30px; margin-bottom: 10px; text-transform: uppercase; }
        .code-block { background: #0f172a; color: #f8fafc; padding: 20px; border-radius: 10px; font-family: monospace; font-size: 11px; white-space: pre-wrap; overflow-x: hidden; }
        h1, h2, h3 { color: #1e293b; margin-top: 25px; }
        ul { padding-left: 20px; }
        li { margin-bottom: 5px; }
      </style>
    </div>
  `;

  // 2. Render to a temporary container
  const container = document.createElement('div');
  container.style.position = 'absolute';
  container.style.left = '-9999px';
  container.style.top = '0';
  container.innerHTML = fullHtml;
  document.body.appendChild(container);

  try {
    // 3. Capture as Image using html2canvas
    const element = document.getElementById('pdf-template');
    if (!element) throw new Error("Template not found");
    
    const canvas = await html2canvas(element, {
      scale: 2, // Higher resolution
      useCORS: true,
      logging: false,
      backgroundColor: '#f8fafc'
    });
    
    const imgData = canvas.toDataURL('image/png');
    
    // 4. Create PDF using jsPDF
    const pdf = new jsPDF({
      orientation: 'p',
      unit: 'mm',
      format: 'a4'
    });
    
    const imgProps = pdf.getImageProperties(imgData);
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
    
    // Handle multi-page if content is long
    let heightLeft = pdfHeight;
    let position = 0;
    const pageHeight = pdf.internal.pageSize.getHeight();

    pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight);
    heightLeft -= pageHeight;

    while (heightLeft >= 0) {
      position = heightLeft - pdfHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight);
      heightLeft -= pageHeight;
    }
    
    // 5. Download
    pdf.save(`AI-Diagnostic-${run.id.slice(0, 8)}.pdf`);
    
  } finally {
    document.body.removeChild(container);
  }
}

function parseMetrics(run: any) {
  if (!run.playwright_output) return null;
  if (run.repo_url !== 'Code Snippet Debugging') {
    return {
      type: 'playwright',
      duration: run.total_duration?.toFixed(1) || '0',
      framework: run.framework_signature || 'N/A'
    };
  }
  const output = run.playwright_output;
  const errorType = output.match(/\*\*Error Type\*\*:\s*(.+)/i)?.[1]?.trim() || 'Analysis Complete';
  const errorLine = output.match(/\*\*Line Number\*\*:\s*(.+)/i)?.[1]?.trim() || 'N/A';
  return {
    type: 'snippet',
    errorType,
    errorLine,
    hasFix: output.includes('### 🚀 3.')
  };
}

function escapeHtml(text: string) {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;');
}
